version: 2
updates:
- package-ecosystem: pip
  directory: "/{{cookiecutter.project_package}}"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/{{cookiecutter.project_package}}/frontend"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.13.10
    - 7.13.9
