name: Test {{ cookiecutter.project_title }} 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install docker-compose
    - name: Run Tests
      run: |
        make test
    - name: Lint Code
      run: |
        make lint
